spring.application.name=billing-service
server.port=8080

# Região da AWS
spring.cloud.aws.region.static=${AWS_REGION:us-east-2}
cloud.aws.stack.auto=false

# Token do Mercado Pago (Injetado via Secret no Kubernetes)
mercadopago.access-token=${MERCADO_PAGO_ACCESS_TOKEN}
