spring.application.name=billing-service
server.port=8080

# ---------------------------------------------------------
# PROFILE: DESENVOLVIMENTO / STAGE (LOCALSTACK)
# ---------------------------------------------------------
# Credenciais e Região
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.region.static=us-east-1

# Endpoints explícitos (Sem o uso de ${...} para evitar o erro de URI)
spring.cloud.aws.endpoint=http://localhost:4566
spring.cloud.aws.sqs.endpoint=http://localhost:4566
spring.cloud.aws.sns.endpoint=http://localhost:4566
spring.cloud.aws.dynamodb.endpoint=http://localhost:4566

# ---------------------------------------------------------
# CONFIGURAÇÕES STRIPE (SANDBOX)
# ---------------------------------------------------------
stripe.api.key=${STRIPE_API_KEY:sua_chave_injetada_aqui}

