{{- if eq .Values.springProfile "dev" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "oficinadb"
            - name: POSTGRES_USER
              value: "mock_user"
            - name: POSTGRES_PASSWORD
              value: "mock_pass"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
{{- end }}