# Caminho: templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: oficina-db-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # O Helm pegará o valor de .Values e converterá para Base64 automaticamente
  username: {{ .Values.db.username |default "mock_user"| b64enc }}
  password: {{ .Values.db.password |default "mock_pass"| b64enc }}