apiVersion: v1
kind: Secret
metadata:
  name: oficina-db-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  # O Helm vai injetar os valores do GitHub Secrets aqui na hora do deploy
  username: {{ .Values.db.username | quote }}
  password: {{ .Values.db.password | quote }}