apiVersion: v1
kind: Secret
metadata:
  name: oficina-auth-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  # O Helm vai injetar o valor dinamicamente aqui na hora do deploy
  JWT_SECRET_ENV: {{ .Values.auth.jwtSecret | quote }}