apiVersion: v1
kind: ServiceAccount
metadata:
  # Alterado para ler diretamente do values.yaml em vez de usar o include com erro
  name: {{ .Values.serviceAccount.name | default "default" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}