# Caminho: templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "billing.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "billing.labels" . | nindent 4 }}