spring.application.name=billing-service
server.port=8080

# ---------------------------------------------------------
# PROFILE: DESENVOLVIMENTO / STAGE (LOCALSTACK)
# ---------------------------------------------------------
# Credenciais e Região
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.region.static=us-east-1

# Endpoints dinâmicos com Fallback para localhost (Resolve o erro de URI e aceita injeção do Helm)
spring.cloud.aws.endpoint=${SPRING_CLOUD_AWS_ENDPOINT:http://localhost:4566}
spring.cloud.aws.sqs.endpoint=${SPRING_CLOUD_AWS_ENDPOINT:http://localhost:4566}
spring.cloud.aws.sns.endpoint=${SPRING_CLOUD_AWS_ENDPOINT:http://localhost:4566}
spring.cloud.aws.dynamodb.endpoint=${SPRING_CLOUD_AWS_ENDPOINT:http://localhost:4566}

# ---------------------------------------------------------
# CONFIGURAÇÕES STRIPE (SANDBOX)
# ---------------------------------------------------------
stripe.api.key=${STRIPE_API_KEY:sua_chave_injetada_aqui}