spring.application.name=billing-service
server.port=8080

# Região da AWS
spring.cloud.aws.region.static=${AWS_REGION:us-east-2}
cloud.aws.stack.auto=false

# Ativa automaticamente o profile "dev" para usarmos o LocalStack
spring.profiles.active=dev
